<a href="https://colab.research.google.com/github/jbl302/test/blob/main/pytorch_nitish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

x = torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [ ]:
y = x**2


In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
z = torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
# z.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
a = torch.tensor(2.0,requires_grad=True)
a

tensor(2., requires_grad=True)

In [ ]:

y = x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:

y.backward()

In [ ]:
x.grad

tensor(12.)

In [ ]:
x.grad.zero_()


tensor(0.)

Creating a simple neural network nn

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.drop(columns = ['id','Unnamed: 32'],inplace = True)

In [ ]:
df.head()
df.columns
df.shape

(569, 31)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.68639776, -0.63812308, -0.55790173, ...,  1.12348445,
         4.70366576,  1.05950995],
       [-0.56672648,  0.17776027, -0.53808794, ..., -0.51517199,
        -0.31859479,  0.24942786],
       [-0.26754828, -1.06728716, -0.32054896, ..., -0.21698058,
        -1.43610921, -1.21049423],
       ...,
       [-0.73768545, -0.26083598, -0.66563926, ...,  0.42687704,
        -0.39888541,  0.48840485],
       [-0.61231554, -1.54361212, -0.64665104, ..., -0.68009263,
        -0.6381187 , -0.27232933],
       [ 1.82100046,  2.36838348,  1.96464233, ...,  2.34138381,
         1.93937423,  2.223899  ]])

In [ ]:
y_train.value_counts()

diagnosis
B    284
M    171
Name: count, dtype: int64

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

numpy array to tensor

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor[0]

tensor([-0.6864, -0.6381, -0.5579, -0.6565,  0.9178,  1.2933,  0.9887,  0.6441,
         3.1782,  1.6347, -0.3062,  0.3812, -0.2930, -0.3591, -0.5224,  0.6644,
         0.5740,  1.1157,  4.3252,  0.3791, -0.5449,  0.1143, -0.4750, -0.5266,
         0.2843,  1.0396,  0.8757,  1.1235,  4.7037,  1.0595],
       dtype=torch.float64)

Creating a simple nn

In [ ]:
class piddu_nn():
  def __init__(self,x):

    self.weights = torch.rand(x.shape[1],1, dtype=torch.float64 , requires_grad=True)
    self.bias = torch.zeros(1,dtype = torch.float64, requires_grad = True)


  def forward(self,x):

    z = torch.matmul(x, self.weights) + self.bias # 569x32 multiplied with  32x1
    self.debug = z
    result = torch.sigmoid(z)

    return result

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    # print(loss)
    return loss



In [ ]:
learning_rate = .01
epochs = 20


In [ ]:
model = piddu_nn(X_train_tensor)
# model.weights

# model.bias

Training pipeline

In [ ]:

# loop
for i in range(0,epochs):
# forward pass that is applying wx+b and calculating sigmoid
  y_pred = model.forward(X_train_tensor)
  # model.looking()

  # print(y_pred)
# loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  print(loss.item())

# backpropagate or gradient calculate
  loss.backward()

# update weights and bias
  with torch.no_grad():  # for these process do not track the gradients
    model.weights-= learning_rate* model.weights.grad
    model.bias -= learning_rate* model.bias.grad

# reseting the gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch {i+1} : loss is {loss.item()}')



3.3910945963170898
Epoch 1 : loss is 3.3910945963170898
3.3763316210657215
Epoch 2 : loss is 3.3763316210657215
3.361466629875084
Epoch 3 : loss is 3.361466629875084
3.346601093309539
Epoch 4 : loss is 3.346601093309539
3.3314710729935473
Epoch 5 : loss is 3.3314710729935473
3.3163584796973886
Epoch 6 : loss is 3.3163584796973886
3.3012634961464706
Epoch 7 : loss is 3.3012634961464706
3.28618630969259
Epoch 8 : loss is 3.28618630969259
3.271127112437597
Epoch 9 : loss is 3.271127112437597
3.2560190489785343
Epoch 10 : loss is 3.2560190489785343
3.2407562054111447
Epoch 11 : loss is 3.2407562054111447
3.2254479954602173
Epoch 12 : loss is 3.2254479954602173
3.209986984200836
Epoch 13 : loss is 3.209986984200836
3.194330637553164
Epoch 14 : loss is 3.194330637553164
3.178694132490937
Epoch 15 : loss is 3.178694132490937
3.1630777118308555
Epoch 16 : loss is 3.1630777118308555
3.1474400874033046
Epoch 17 : loss is 3.1474400874033046
3.1316122742995836
Epoch 18 : loss is 3.1316122742995836

NN module and optim module
- NN module: providing inbuilt classes and functions, prebuilt layers, loss functions, utility functions
- nn.layer, nn.conv2d, nn.lstm
- relu, sigmoid, tanh, crossentropy loss, log loss etc.
- Regularization, dropout layers



In [ ]:
# create model class
# our model has 5 inputs and one output
import torch
import torch.nn as nn

class model_with_nn(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):

    out = self.linear(features) # wx+b
    out = self.sigmoid(out) # calculating sigmoid with the output of wx+b

    return out




In [ ]:
# creating dataset
features = torch.rand(10,5)


# create model
model = model_with_nn(features.shape[1]) # number of columns

# calling forward
model(features) # this will trigger forward method
print(features)


tensor([[0.1948, 0.9527, 0.0272, 0.4879, 0.8416],
        [0.2895, 0.2692, 0.2494, 0.7930, 0.7039],
        [0.3603, 0.6126, 0.6812, 0.5227, 0.4452],
        [0.6456, 0.5834, 0.9215, 0.3693, 0.1878],
        [0.0697, 0.3487, 0.6663, 0.5250, 0.3059],
        [0.8611, 0.3431, 0.3351, 0.7244, 0.2103],
        [0.7995, 0.4815, 0.1015, 0.9596, 0.3309],
        [0.7807, 0.3735, 0.0028, 0.0709, 0.5361],
        [0.1496, 0.6671, 0.6936, 0.4555, 0.2381],
        [0.9557, 0.0130, 0.7491, 0.2646, 0.1763]])


In [ ]:
model.linear.weight
model.linear.bias


Parameter containing:
tensor([-0.0505], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:

from torchinfo import summary

summary(model,input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model_with_nn                            [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Creating a hidden layer
5 input 3 hidden and one ouput
- total weights 5x3 + 3x1 = 18
- total biases 3+1 = 4

In [ ]:
import torch
import torch.nn as nn

class model_with_nn(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features,3) # 5 inputs 3 outputs for input layer
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1) # for hidden layer 3 inputs 1 output
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):

    out = self.linear1(features) # wx+b
    out = self.relu(out) # calculating sigmoid with the output of wx+b
    out = self.linear2(out)
    out  = self.sigmoid(out)

    return out


In [ ]:
# create model
model = model_with_nn(features.shape[1]) # number of columns

# calling forward
model(features) # this will trigger forward method
print(features)



tensor([[0.1948, 0.9527, 0.0272, 0.4879, 0.8416],
        [0.2895, 0.2692, 0.2494, 0.7930, 0.7039],
        [0.3603, 0.6126, 0.6812, 0.5227, 0.4452],
        [0.6456, 0.5834, 0.9215, 0.3693, 0.1878],
        [0.0697, 0.3487, 0.6663, 0.5250, 0.3059],
        [0.8611, 0.3431, 0.3351, 0.7244, 0.2103],
        [0.7995, 0.4815, 0.1015, 0.9596, 0.3309],
        [0.7807, 0.3735, 0.0028, 0.0709, 0.5361],
        [0.1496, 0.6671, 0.6936, 0.4555, 0.2381],
        [0.9557, 0.0130, 0.7491, 0.2646, 0.1763]])


In [ ]:
model.network[0].weight # 3x5
# model.linear2.weight

Parameter containing:
tensor([[ 0.3527,  0.0256, -0.2324, -0.0923,  0.3415],
        [ 0.1381,  0.0168, -0.1344, -0.3944, -0.1719],
        [-0.0126,  0.0873, -0.2368, -0.2654, -0.4260]], requires_grad=True)

In [ ]:
import torch
import torch.nn as nn

class model_with_nn(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential( nn.Linear(num_features,3) ,# 5 inputs 3 outputs for input layer
    nn.ReLU(),
    nn.Linear(3,1), # for hidden layer 3 inputs 1 output
    nn.Sigmoid()) # sequential container



  def forward(self, features):

    out =  self.network(features)

    return out

Improvements in mysimplenn

In [ ]:

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
y_train_tensor = y_train_tensor.double()
y_train_tensor.dtype
# y_pred.dtype

torch.float64

In [ ]:
model = MySimpleNN(X_test_tensor.shape[1])
model = model.double() # converting every weight and bias to double

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# loop
y_train_tensor = y_train_tensor.double()
for i in range(0,epochs):
# forward pass that is applying wx+b and calculating sigmoid
  y_pred = model.forward(X_train_tensor)
  # model.looking()

  # print(y_pred)
# loss calculate

  loss = loss_function(y_pred,y_train_tensor.view(-1,1))
  print(loss.item())

# backpropagate or gradient calculate


# update weights and bias
  # with torch.no_grad():  # for these process do not track the gradients
  #   model.linear.weight-= learning_rate* model.linear.weight.grad
  #   model.linear.bias -= learning_rate* model.linear.bias.grad
  optimizer.step()
  loss.backward()
# reseting the gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  optimizer.zero_grad()

  print(f'Epoch {i+1} : loss is {loss.item()}')



0.6493206601209012
Epoch 1 : loss is 0.6493206601209012
0.6493206601209012
Epoch 2 : loss is 0.6493206601209012
0.6493206601209012
Epoch 3 : loss is 0.6493206601209012
0.6493206601209012
Epoch 4 : loss is 0.6493206601209012
0.6493206601209012
Epoch 5 : loss is 0.6493206601209012
0.6493206601209012
Epoch 6 : loss is 0.6493206601209012
0.6493206601209012
Epoch 7 : loss is 0.6493206601209012
0.6493206601209012
Epoch 8 : loss is 0.6493206601209012
0.6493206601209012
Epoch 9 : loss is 0.6493206601209012
0.6493206601209012
Epoch 10 : loss is 0.6493206601209012
0.6493206601209012
Epoch 11 : loss is 0.6493206601209012
0.6493206601209012
Epoch 12 : loss is 0.6493206601209012
0.6493206601209012
Epoch 13 : loss is 0.6493206601209012
0.6493206601209012
Epoch 14 : loss is 0.6493206601209012
0.6493206601209012
Epoch 15 : loss is 0.6493206601209012
0.6493206601209012
Epoch 16 : loss is 0.6493206601209012
0.6493206601209012
Epoch 17 : loss is 0.6493206601209012
0.6493206601209012
Epoch 18 : loss is 0.

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5
